services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=curso_sprinboot'
      - 'POSTGRES_PASSWORD=a1b2c3d4'
      - 'POSTGRES_USER=devdb'
    ports:
      - '5432:5432'
