INSERT INTO noticia (id, titulo, texto, autor, imagen, fecha, eliminada, programa, importancia, lugar, diurna, nocturna, evento, noticia) VALUES
                                                                                                                                              ('1', 'Título de la noticia 1', 'Texto de la noticia 1', 'Autor 1', 'imagen1.jpg', '2024-10-01', FALSE, 'Programa A', 'Alta', 'Lugar 1', TRUE, FALSE, TRUE, TRUE),
                                                                                                                                              ('2', 'Título de la noticia 2', 'Texto de la noticia 2', 'Autor 2', 'imagen2.jpg', '2024-10-02', FALSE, 'Programa B', 'Media', 'Lugar 2', FALSE, TRUE, FALSE, TRUE),
                                                                                                                                              ('3', 'Título de la noticia 3', 'Texto de la noticia 3', 'Autor 3', 'imagen3.jpg', '2024-10-03', TRUE, 'Programa C', 'Baja', 'Lugar 3', TRUE, FALSE, TRUE, FALSE),
                                                                                                                                              ('4', 'Título de la noticia 4', 'Texto de la noticia 4', 'Autor 4', 'imagen4.jpg', '2024-10-04', FALSE, 'Programa A', 'Alta', 'Lugar 1', FALSE, TRUE, TRUE, TRUE),
                                                                                                                                              ('5', 'Título de la noticia 5', 'Texto de la noticia 5', 'Autor 5', 'imagen5.jpg', '2024-10-05', TRUE, 'Programa B', 'Media', 'Lugar 2', TRUE, FALSE, FALSE, TRUE),
                                                                                                                                              ('6', 'Título de la noticia 6', 'Texto de la noticia 6', 'Autor 6', 'imagen6.jpg', '2024-10-06', FALSE, 'Programa C', 'Baja', 'Lugar 3', FALSE, TRUE, TRUE, FALSE),
                                                                                                                                              ('7', 'Título de la noticia 7', 'Texto de la noticia 7', 'Autor 7', 'imagen7.jpg', '2024-10-07', TRUE, 'Programa A', 'Alta', 'Lugar 1', TRUE, FALSE, FALSE, TRUE),
                                                                                                                                              ('8', 'Título de la noticia 8', 'Texto de la noticia 8', 'Autor 8', 'imagen8.jpg', '2024-10-08', FALSE, 'Programa B', 'Media', 'Lugar 2', FALSE, TRUE, TRUE, TRUE),
                                                                                                                                              ('9', 'Título de la noticia 9', 'Texto de la noticia 9', 'Autor 9', 'imagen9.jpg', '2024-10-09', TRUE, 'Programa C', 'Baja', 'Lugar 3', TRUE, FALSE, FALSE, FALSE),
                                                                                                                                              ('10', 'Título de la noticia 10', 'Texto de la noticia 10', 'Autor 10', 'imagen10.jpg', '2024-10-10', FALSE, 'Programa A', 'Alta', 'Lugar 1', FALSE, TRUE, TRUE, TRUE);